FROM node:22-alpine

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml tsconfig.json ./
COPY scripts ./scripts
COPY src ./src
COPY monitor ./monitor
COPY config ./config
COPY plugins ./plugins

RUN pnpm install --frozen-lockfile

EXPOSE 3001 4310

CMD ["pnpm", "event-api"]
