apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: project-external-secrets
  namespace: __PROJECT_NAMESPACE__
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: sprintfoundry-aws-secretsmanager
  target:
    name: project-runtime-secrets
    creationPolicy: Owner
  dataFrom:
    - find:
        path: sprintfoundry/projects/__PROJECT_ID__
