apiVersion: v1
kind: ResourceQuota
metadata:
  name: project-quota
  namespace: __PROJECT_NAMESPACE__
spec:
  hard:
    requests.cpu: "20"
    limits.cpu: "20"
    requests.memory: 40Gi
    limits.memory: 40Gi
    count/jobs.batch: "50"
