{{- if and .Values.snapshot.enabled (not .Values.snapshot.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sprintfoundry.snapshotSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sprintfoundry.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.snapshot.awsAccessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.snapshot.awsAccessKeyId | quote }}
  {{- end }}
  {{- if .Values.snapshot.awsSecretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.snapshot.awsSecretAccessKey | quote }}
  {{- end }}
{{- end }}
