apiVersion: v1
kind: Service
metadata:
  name: {{ include "sprintfoundry.fullname" . }}-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sprintfoundry.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitor
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "sprintfoundry.name" . }}-monitor
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.monitor.port }}
      targetPort: http
